# Generated by Django 3.0.6 on 2020-05-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200512_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='title',
        ),
    ]
