# Generated by Django 3.0.6 on 2020-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200512_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='additional_information',
            field=models.TextField(blank=True),
        ),
    ]
